travis:
  secure:
    BINSTAR_TOKEN: QfHgD3vPaNxgMKNPe67V4V3n1Eqfup8sGiVxifrsgaIjWUMSpEdFN6CcZBzO4axT36pzoEbyveT5v75Nwnj8cvZtx1Nxm+fsBAN5w0JnCaqUO8uU8OR9rPOia+vyua1tVAEGP7zxz8LlzYdsRi3kdzqL98E2nVObHB22/OMR5zDRVcNmVtsy9uljez46F2F3rhy9vO+/m4ibPhB30gT8tfqMpiB2kKKJpCbV0iihpX7ZyI4Z2lwNf8IB8Yxh+4Nd2gIkcjiyEv+Ycmq/d4ns2fp7dApj+TFNeD9mK9uPnwVSYxrq1JYVscMxWVgPEdjbvqJB4t2igcvACax/2a7Sn7RtUYT+O5xsNkDQ0ey0oV0N8YrqE6K5u0HQ9vykS759ctHIUfF20zMaKaqbverWH+H17XwrjwsKVfg+B4gEcTTcj+Q9Au6l3/oB/lU1YUAQ6gnoUIHzxed/qHb1oWKvJGP0rDumQUMhd1VUQdXKOl4SRJs3GhGEdtveLXfGipT/AEYV9q3eevnRwl/luV/3HPnUfGFYTmGE+AOquCoy2lXihOIinYN40wLdC6oVOsi7wf4NNSbR4WOjvkKvcTgH/h3K7virqVmyOgJY8LiPQ2bOmrZ7y8e6Rg86TYI5fvRs3oogZbG4TVdqDhzazpoYZzpE/jZGiam49t1v+KoB8Z0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
