travis:
  secure:
    BINSTAR_TOKEN: uBeaDcfy13DPxjxCcKR1fo9ESUEdp7ZuVfR2eBxAgcnLvR+tYTKJDDJxwmYAtthEwgrrF/amFDvXu0O5Xb7puZF3qLtwMxhx6ZdFEupyaXZyjh9mjUqIujsr0SHzamSqEa3b7IEBbYVwgwN07k6RTPCdnzhOT3991DbMmuQavDAI1jTnACzUNbRCkn/YeiObdN0gEuQ7auUZ7eMhguTc1zwKPXhO6d/Gio1xo+p36IRSTsHfMwgrv/xeCotC4S8vpmABM1itvafpT+ZGfi9d/xobig8rqBhIPZfvVnZS+nisNS2cn5ylhCQhiIIRs74PWzTieCEtidKxXeQQLikrflGHqdXEaymaVXXMSK5Jc+FJkU5bMhru5FoXVX6qnV84d/OXMoZEc+AtQydC1j5ULGDrtf3MeqCqJ+0mmhqbua/qx5QCGx379sFaLRjD3s5AWaeqj9QN+F6gTJkHktdaud/aKxALTg+yuMmy4QQGvHu4qlnhERkBbfn18LKfEopSLteBTy4YLYfLTHwC3xL2WxEsdYS4lJMaPa4G5AO7aFaBS41WpAJIN63G5/NcQAtKU9q10ePjLAQTpNxgaAXtrBP+bWXVZA/lc7aGgiu/rL1hyRLcMgC4HNSjFjTq3Db9vnAxWDzfF9E0ZgrsZsrcWOEUzz1EtoAU9Y9zGxVT+UE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
